{"uuid":"4fb2e0aa-5f9e-45f9-b5ee-345dbac1d0d0","historyId":"dcbbc66ed78313efaf2d9c9063409774","fullName":"EmployeeTests.addEmployeeTest","labels":[{"name":"package","value":"EmployeeTests"},{"name":"testClass","value":"EmployeeTests"},{"name":"testMethod","value":"addEmployeeTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"soap-services-integration-homework"},{"name":"subSuite","value":"EmployeeTests"},{"name":"host","value":"DESKTOP-3QHAGIK"},{"name":"thread","value":"9620@DESKTOP-3QHAGIK.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"addEmployeeTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n### The error may exist in ge/tbc/testautomation/EmployeeMapper.java (best guess)\r\n### The error may involve ge.tbc.testautomation.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n","trace":"org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n### The error may exist in ge/tbc/testautomation/EmployeeMapper.java (best guess)\r\n### The error may involve ge.tbc.testautomation.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n\tat org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)\r\n\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)\r\n\tat org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)\r\n\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)\r\n\tat jdk.proxy2/jdk.proxy2.$Proxy12.insertEmployee(Unknown Source)\r\n\tat ge.tbc.testautomation.EmployeeSteps.insertEmployeeIntoDB(EmployeeSteps.java:75)\r\n\tat EmployeeTests.addEmployeeTest(EmployeeTests.java:12)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.engine.SessionRemote.readSQLException(SessionRemote.java:663)\r\n\tat org.h2.engine.SessionRemote.readException(SessionRemote.java:646)\r\n\tat org.h2.engine.SessionRemote.done(SessionRemote.java:620)\r\n\tat org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:225)\r\n\tat org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:262)\r\n\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)\r\n\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)\r\n\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\r\n\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)\r\n\t... 32 more\r\n"},"stage":"finished","steps":[{"name":"Prepare employee info for addition","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1750599407039,"stop":1750599407049},{"name":"Insert employee into H2 database","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n### The error may exist in ge/tbc/testautomation/EmployeeMapper.java (best guess)\r\n### The error may involve ge.tbc.testautomation.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n","trace":"org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n### The error may exist in ge/tbc/testautomation/EmployeeMapper.java (best guess)\r\n### The error may involve ge.tbc.testautomation.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n\tat org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)\r\n\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)\r\n\tat org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)\r\n\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)\r\n\tat jdk.proxy2/jdk.proxy2.$Proxy12.insertEmployee(Unknown Source)\r\n\tat ge.tbc.testautomation.EmployeeSteps.insertEmployeeIntoDB(EmployeeSteps.java:75)\r\n\tat EmployeeTests.addEmployeeTest(EmployeeTests.java:12)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PRIMARY KEY ON PUBLIC.employee(employee_id) ( /* key:8 */ NULL, 50000.00, CAST(8 AS BIGINT), 'Sorcerer Kingdom', 'Sales', 'Saba_Kvevesqiri@gmail.com', 'Saba', '12345678')\"; SQL statement:\nINSERT INTO Employee (employee_Id, name, department, phone, address, salary, email) VALUES (?, ?, ?, ?, ?, ?, ?) [23505-232]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:121)\r\n\tat org.h2.mvstore.db.MVTable.addRow(MVTable.java:517)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:174)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:139)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:304)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:248)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:386)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:193)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\r\n\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.engine.SessionRemote.readSQLException(SessionRemote.java:663)\r\n\tat org.h2.engine.SessionRemote.readException(SessionRemote.java:646)\r\n\tat org.h2.engine.SessionRemote.done(SessionRemote.java:620)\r\n\tat org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:225)\r\n\tat org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:262)\r\n\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)\r\n\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)\r\n\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\r\n\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)\r\n\t... 32 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1750599407050,"stop":1750599407649}],"attachments":[],"parameters":[],"start":1750599407007,"stop":1750599407655}